# fly.toml app configuration file generated for product-listing-shy-fog-6441 on 2026-03-23T14:11:18+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'product-listing-shy-fog-6441'
primary_region = 'fra'

[build]

[env]
  DATABASE_PATH = '/data/products.db'
  NODE_ENV = 'production'
  PORT = '3001'

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
